name: 'Assert Command Line Output'

description: 'Github Action to assert / check a command line output 🕵️⚙️🖥'

inputs:
    command_line:
        description: 'The command line you want to run'
        required: true
    assert_file_path:
        description: 'Path to assert file to compare. e.g: repo/path/file.txt'
        required: false
    specific_line:
        description: 'Assert file line to compare with the command line output file'
        required: false
    contains:
        description: 'Expression the command line output file must contain'
        required: false
    expected_result:
        description: 'PASSED or FAILED'
        required: false
        default: 'PASSED'

outputs:
  diff-output:
    description: "Assert output"
    value: ${{ steps.assert.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: install strip-ansi-cli
      run: |
        if [ -z "${{ inputs.contains }}" ]; then
            echo 🚧 Installing strip-ansi-cli
            npm install --global strip-ansi-cli
        fi
      shell: bash

    - name: Create command output file
      run: |
        ${{ inputs.command_line }} &> output.txt || true
        echo 🚀 Command OUTPUT exported to output.txt file
      shell: bash

    - name: Assert
      id: assert
      run: |
        if [ ! -z "${{ inputs.contains }}" ]; then
            echo 🕵️ Check if output file contains expression \"${{ inputs.contains }}\"
            if grep -q "${{ inputs.contains }}" output.txt; then
                result=$(echo "PASSED")
            else
                result=$(echo "FAILED")
            fi
        elif [ ! -z ${{ inputs.specific_line }} ]; then
            echo 🕵️ Comparing files specific line
            if diff --strip-trailing-cr -a <(head -n ${{ inputs.specific_line }} output.txt | strip-ansi ) <(head -n ${{ inputs.specific_line }} ${{ inputs.assert_file_path }} | strip-ansi ) >/dev/null; then
                result=$(echo "PASSED")
            else
                result=$(echo "FAILED")
            fi
        else
            echo 🕵️ Comparing files
            if diff --strip-trailing-cr -a <(cat output.txt | strip-ansi) <(cat ${{ inputs.assert_file_path }} | strip-ansi) >/dev/null; then
                result=$(echo "PASSED")
            else
                result=$(echo "FAILED")
            fi
        fi
        echo "result=$(echo $result)" >> $GITHUB_OUTPUT
      shell: bash

    - name: GOT vs EXPECTED
      run: |
        echo ▶️ GOT: ${{ steps.assert.outputs.result }}
        echo ▶️ EXPECTED: ${{ inputs.expected_result }}
        if [ ${{ steps.assert.outputs.result }} != ${{ inputs.expected_result }} ]; then
            echo 🆚 GOT != EXPECTED ❌
            if [ ! -z "${{ inputs.contains }}" ]; then
                echo "Command output doesn't contain \"${{ inputs.contains }}\""
                cat output.txt
            elif [ ! -z ${{ inputs.specific_line }} ]; then
                diff --strip-trailing-cr -a <(head -n ${{ inputs.specific_line }} output.txt | strip-ansi ) <(head -n ${{ inputs.specific_line }} ${{ inputs.assert_file_path }} | strip-ansi ) | cat -t
            else
                diff --strip-trailing-cr -a <(cat output.txt | strip-ansi) <(cat ${{ inputs.assert_file_path }} | strip-ansi) | cat -t
            fi
            exit 1
        else
            echo 🆚 GOT = EXPECTED ✅
        fi
      shell: bash

branding:
    icon: 'check'
    color: 'green'
