name: Action test on MacOs (V1)

on:
  push:
  workflow_dispatch:

jobs:
  PASSED-assert-file:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: GuillaumeFalourd/test-cli-commands-action@v1
        with:
          command_line: cat action.yml
          assert_file_path: action.yml
          expected_result: PASSED

  FAILED-assert-file:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: GuillaumeFalourd/test-cli-commands-action@v1
        with:
          command_line: ls -lha
          assert_file_path: assert.txt
          expected_result: FAILED

  PASSED-specific-line:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: GuillaumeFalourd/test-cli-commands-action@v1
        with:
          command_line: cat action.yml
          assert_file_path: action.yml
          expected_result: PASSED
          specific_line: 1

  FAILED-specific-line:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: GuillaumeFalourd/test-cli-commands-action@v1
        with:
          command_line: ls -lha
          assert_file_path: assert.txt
          expected_result: FAILED
          specific_line: 2

  PASSED-contains:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: GuillaumeFalourd/test-cli-commands-action@v1
        with:
          command_line: ls -lha
          contains: runner
          expected_result: PASSED

  FAILED-contains:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: GuillaumeFalourd/test-cli-commands-action@v1
        with:
          command_line: ls -lha
          contains: error
          expected_result: FAILED
